### ISSUE TITLE
Obsolete class org.cocome.tradingsystem.inventory.data.test.StoreQueryImplTest

### ISSUE THREAD

**Issue by rju** [cocome-community-case-study/cocome-cloud-jee-service-adapter#1]
The class `org.cocome.tradingsystem.inventory.data.test.StoreQueryImplTest` is only one large comment. As it is obviously not used, I have renamed it to `StoreQueryImplTest.java.txt`. It has no purpose. I wonder why it is still here. Does anybody have an idea whether we should keep it.

**Comment by Benkler** [comment]
Removed
