### ISSUE TITLE
Main method in cocome.cloud.sa.query.SelectQuery

### ISSUE THREAD

**Issue by rju** [cocome-community-case-study/cocome-cloud-jee-service-adapter#3]
`cocome.cloud.sa.query.SelectQuery` (service-adapter-rest) is not a main class, as it is part of a restful service. Therefore, it might be some test code, but it is neither labeled that way nor is this the right place for test code. Therefore, I commented it out, but created this issue.

**Comment by rju** [comment]
The same applies to `cocome.cloud.sa.query.parsing.QueryParser`

**Comment by Benkler** [comment]
Both code snippets were deleted.
