### ISSUE TITLE
Undocumented strange interface IQueryConst

### ISSUE THREAD

**Issue by rju** [cocome-community-case-study/cocome-cloud-jee-service-adapter#5]
`IQueryConst` is only used in `ServiceProviderDatabase` and defines a set of strings. However, an interface should define methods (that is it sole purpose). Either convert the interface to a class with constants (which would still be ugly, but at least not a total misuse of the concept interface). 

However, the first four strings in the class look like three different states to identify query types (this could be implemented as an enumeration which would also fix a lot of problems with the case statements.)  The remaining strings look like a configuration of some serializer. They should be moved where this serializer is.

**Comment by Benkler** [comment]
Interface changed to class. Cannot use enum as Strings are used in switch case statement. (No method calls possible)!
